export const ERROR_CODES = Object.freeze({
  INVALID_NORMALIZED_FEEDBACK: "INVALID_NORMALIZED_FEEDBACK",
  ANALYSIS_FAILED: "ANALYSIS_FAILED",
  ANALYSIS_SCHEMA_INVALID: "ANALYSIS_SCHEMA_INVALID",
  ANALYSIS_PROVIDER_RATE_LIMITED: "ANALYSIS_PROVIDER_RATE_LIMITED",
  EMBEDDING_FAILED: "EMBEDDING_FAILED",
  CLUSTERING_FAILED: "CLUSTERING_FAILED",
  AGGREGATION_FAILED: "AGGREGATION_FAILED",
  UNSUPPORTED_TAXONOMY_VALUE: "UNSUPPORTED_TAXONOMY_VALUE",
});
